# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-client:
    docker:
      - image: circleci/node:10
    working_directory: ~/summer-camp-live-map/client

    steps:
      - checkout:
          path: ~/summer-camp-live-map

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run flow
      - run: yarn flow --quiet

  deploy-backend:
    machine:
        enabled: true
    working_directory: ~/summer-camp-live-map/server
    environment:
      HEROKU_APP: "live-map-api"
      HEROKU_API_KEY: "965af484-a02d-4b72-959e-fa9cd96cc5eb"
    steps:
      - checkout:
          path: ~/summer-camp-live-map
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master


workflows:
  version: 2
  tests:
    jobs:
      - test-client
  deploy:
    jobs:
      - deploy-backend:
          filters:
            branches:
              only: master